site_name: TASNADI AI
site_description: Your site description
site_url: https://tasnadi-ai.de

nav:
  - Home:
    - About me: index.md
  # - Portfolio:
  #   - Overview: portfolio/index.md
  #   - Projects:
  #     - portfolio/projects/project-1.md
  #     - portfolio/projects/project-2.md
  - Book a free intro call: book-a-call.md 

theme:
  name: material
  features:
    - search.suggest
    - toc.integrate
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom  
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
  font:
    text: Montserrat
    code: Roboto Mono
  favicon: assets/logo-mark.png

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/borbalita
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/borbála-t-826534103/
  analytics:
    # provider: google
    # property: G-W9Y130NXVZ

extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css
exclude_docs: |
  blog/
  portfolio/

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#050505"
        color: "#F5F1E3"

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.keys

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js

extra_files:
  - docs/robots.txt

copyright: |
  &copy; 2026 <a href="https://www.linkedin.com/in/borbála-t-826534103/" target="_blank" rel="noopener">Borbála Tasnádi</a>. All rights reserved.